### ISSUE TITLE
Using dotenv means secrets in repo

### ISSUE THREAD

**Issue by mryellow** [vencax/netlify-cms-github-oauth-provider#1]
For this kind of secret I usually create a `setup_env.sh` and `setup_env.example.sh` then `.gitignore` the non-example version. This way secrets don't end up committed to repositories.

**Comment by vencax** [comment]
This actually prevents to have the secrets in repo. You just create .env file in your deployment env and the app will load it and set the envvars appropriately. So you dont need to create another script and mess up your env. See https://www.npmjs.com/package/dotenv for details.
