### ISSUE TITLE
Not working on sub page

### ISSUE THREAD

**Issue by tumble1999** [vencax/netlify-cms-github-oauth-provider#10]
I forked your app and replaced app.listen with module.exports = app and in my main app, I used app.use to mount it. that all works.

When I do app.use("/netlify",varReferingToNetlifyAuthProv)
(and set backend.base_url and oath Authorization callback URL acordingly)
it gets stuck at /netlify/callback?code=***&state=*** but when I do app.use without a mount path (and set backend.base_url and oath Authorization callback URL acordingly) it goes to /callback?code=***&state=*** and the window closes and netlify sucessfully loges in.

Github fork: https://github.com/tumblenet/netlify-cms-github-oauth-provider
API Server code: https://github.com/tumblenet/api.tumblenet.ga
static website with the cms: https://github.com/tumblenet/go.tumblenet.cu.cc

**Comment by vencax** [comment]
Hi man, sorry for delay. Please suggest right solution to let the discussion continue. Thanks

**Comment by robsonsobral** [comment]
Hi, @vencax !

We're having the same issue, trying to run on a subdirectory of the same domain of the NetlifyCMS: `domain.com\auth`.

Any idea? Thank you!

**Comment by vencax** [comment]
Hi, it is out of my time possibilities to search the solution now. Please find the solution and send a PR.

**Comment by Eduruiz** [comment]
We solved this by pointing both the oAuth `.env` file and the CMS `base_url` (on config.yml) to our root domain.

**Comment by IvaTsu** [comment]
Hi!

I am not able to make it work on a subdomain as well.

It just gets stuck at the OAuth redirect: `callback?code=bda1f4a5f72cd3a80d35&state=uEjkSEOBYLMMuctrovxhi8C9yRRUOoq8`

Any suggestions?
Thanks

**Comment by walxlgf** [comment]
Add the second parameter in index.js . 
`module.exports = {
  auth: authMiddleWareInit(oauth2),
  callback: callbackMiddleWareInit(oauth2, **oauthProvider**),
  success: (req, res) => { res.send('') },
  index: indexMiddleWare
}`

**Comment by walxlgf** [comment]
> Hi!
> 
> I am not able to make it work on a subdomain as well.
> 
> It just gets stuck at the OAuth redirect: `callback?code=bda1f4a5f72cd3a80d35&state=uEjkSEOBYLMMuctrovxhi8C9yRRUOoq8`
> 
> Any suggestions?
> Thanks


Add the second parameter in index.js  **module.exports**
`callback: callbackMiddleWareInit(oauth2, oauthProvider),`

**Comment by vencax** [comment]
https://github.com/vencax/netlify-cms-github-oauth-provider/commit/bad35f2972691acdfb6397377aa656afc4f0b148 is this what you meant?

**Comment by vencax** [comment]
Find usage of REDIRECT_URL env var.
