### ISSUE TITLE
Too much rights for the app

### ISSUE THREAD

**Issue by severo** [vencax/netlify-cms-github-oauth-provider#11]
I understand that this gives this app too much rights, with the scope "user,repo": write access on all the user information and all its repositories.

Is there a way to limit to write access on a specific repository?

**Comment by vencax** [comment]
Hi, actually I don't know. I am ok with the default. Although you can override the  scope. See:
https://github.com/vencax/netlify-cms-github-oauth-provider/blob/master/index.js#L24

**Comment by severo** [comment]
Answer from Github support:

> Thanks for reaching out. No, that's not possible with OAuth Apps. However, it is possible with GitHub Apps:
> 
> https://developer.github.com/apps/differences-between-apps/
> 
> I understand that this doesn't help you much if you're using an app developed by someone else, but perhaps you can reach out to them and ask if they'd consider switching their app from an OAuth App to a GitHub App.
> 
> I hope this answers your question, but let me know if there's anything else.

**Comment by severo** [comment]
I think the current configuration gives too much rights to whom manages the server where netlify-cms-github-oauth-provider runs, on behalf of the users. Even if there is complete trust between them, the users security depends on the server security.
Maybe it would be better to switch to a GitHub app, instead of a OAuth app. Do you think it would be a solution?

**Comment by vencax** [comment]
I think you misunderstood the concept. OAuht app is an external application that allow to perform action as github user. It operates on user level, which means it can co anything specific user can do.
Although GitHub app is IMHO something else. It is en entity that you can allow specific action on your repositories. But you cannot login as that app. It is kinda bot - software variant of an user. Something like API key. Maybe I am wrong but thats how I understand from brief look ..

**Comment by severo** [comment]
Maybe it's not the solution. But I fear the users could refuse to login seeing the amount of rights they are giving.

**Comment by vnugent** [comment]
I've just set up the app and can see what you are referring to.  This will scare my users away.  
@vencax  can you expand a bit more how to override the scope? I looked at the [link](https://github.com/vencax/netlify-cms-github-oauth-provider/blob/master/index.js#L24), but am not sure what to do there.

<img width="526" alt="Screen Shot 2021-07-20 at 10 50 12 AM" src="https://user-images.githubusercontent.com/3805254/126292392-25037a0f-978f-4066-b7a3-79f7cc9f7c4a.png">

*Edit:   Here's how SCOPES is setup in auth.js
```
  const authorizationUri = oauth2.authorizationCode.authorizeURL({
    redirect_uri: process.env.REDIRECT_URL,
    scope: process.env.SCOPES || 'repo,user',
    state: randomstring.generate(32)
  })
```

**Comment by ncjones** [comment]
The Github OAuth scopes are documented at https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps.

I am going to try using `SCOPES=read:user,public_repo`.
