### ISSUE TITLE
popup window stays open and blank

### ISSUE THREAD

**Issue by itsam** [vencax/netlify-cms-github-oauth-provider#14]
Hi there. I have managed to make everything works (window popups, you are able to authorise github, the OAuth app in github "gets" the new user) BUT eventually the popup window doesn't close and it's just blank... 
Well, actually it contains just

```
<script>
(function() {
    function receiveMessage(e) {
    console.log("receiveMessage %o", e)
    // send message to main window with da app
    window.opener.postMessage(
        'authorization:github:success:{"token":"5b95156e2667db763606e3647d48968054716001","provider":"github"}',
        e.origin
    )
    }
    window.addEventListener("message", receiveMessage, false)
    // Start handshare with parent
console.log(window.opener)
    console.log("Sending message: %o", "github")
    window.opener.postMessage("authorizing:github", "*")
    })()
</script>
```
I believe that for a reason the popup cannot postmessage to the parent window (where netlifycms /admin/#/ is) and vice versa...

Any ideas will be more than welcome. Thanks in advance!

**Comment by itsam** [comment]
Well, I found it eventually. It deals with https://github.com/netlify/netlify-cms/issues/1285 and all I had to do is to change base_url AND ADD  auth_endpoint. Hope that helps someone else.

**Comment by skoldborg** [comment]
@itsam I think I'm having this same issue. What do you set the auth_endpoint variable to exactly?

**Comment by kfazil** [comment]
I was facing the same issue but the difference is I'm using my own auth server (Github) instead of netlify's auth server. The issue was I haven't set the application's 'Homepage URL' and 'Authorization callback URL'  as 'www' subdomain while registering the OAuth application on Github. But on other places (CMS - host, and auth server - orign and redirect_url) I was using subdomain (www) before (apex) domain name.

**Comment by Tobilo** [comment]
Having the same problem. I still get the error, that the window.opener is null. It makes sense that it is null, after the redirect to github and back over the callback url. So how is that supposed to work?
