### ISSUE TITLE
Authenticating Github in backend instead of redirecting to Github login page

### ISSUE THREAD

**Issue by raomaneesh88** [vencax/netlify-cms-github-oauth-provider#15]
I am using this project for doing  Github Authentication through my own server.  I have integrated the Netflify-CMS to my React-App. Once auser is logged into the React-App, he/she needs to do a separate login into Github Account again  to access Netlify-CMS. I am looking for solution that moves the Github login process to backend API/ netlify-cms-github-oauth-provider code where we can store username/password of github account and there itself we perform the login and upon success, it redirects to Netlify-CMS UI directly. 

**This what happens currently**
1. When user login in the react app and move to Netlify-CMS option, below screen appears that prompts the user to  login with github again.
![image](https://user-images.githubusercontent.com/10016729/54232410-98740d80-4530-11e9-9b01-f18915797eac.png)

2. After clicking on "login with Github" , it redirects to github login page with the help of netlify-cms-github-oauth-provider project running on Ec2 server
![image](https://user-images.githubusercontent.com/10016729/54232453-b0e42800-4530-11e9-8a48-000d5876207d.png)

3. After successful login , I can see the netflify-CMS UI
![image](https://user-images.githubusercontent.com/10016729/54232571-ef79e280-4530-11e9-8774-3bbbf3912fd0.png)

**I am looking to move the 2nd step in background ,so that users of my app doesn't need to login into github separately. Is this possible with "netlify-cms-github-oauth-provider" project ??**

**Comment by vencax** [comment]
Sorry, I don't understand your scenario. Please refer to OAuth2 scenario, this project just implement it.
