### ISSUE TITLE
Can I use the same provider for multiple origins?

### ISSUE THREAD

**Issue by pratik-kanthi** [vencax/netlify-cms-github-oauth-provider#25]
I would like to use the same instance of this auth provider to authenticate into netlify-cms for multiple websites. Can the Origin variable be a regex that allows multiple domains?

**Comment by Threnklyn** [comment]
> NOTE: ORIGIN is mandatory and can contain regex (e.g. .*.my_organisation.com)

from the readme

**Comment by vencax** [comment]
I guess that you can. Use appropriate regex. See: https://github.com/vencax/netlify-cms-github-oauth-provider/blob/master/callback.js#L45

**Comment by devcustrom** [comment]
@pratik-kanthi I implemented it like this https://github.com/vencax/netlify-cms-github-oauth-provider/pull/29

**Comment by vencax** [comment]
Now, yes.
