### ISSUE TITLE
Settings for localhost

### ISSUE THREAD

**Issue by scriptology** [vencax/netlify-cms-github-oauth-provider#38]
Hi all!
Could someone help me to set up this provider to work locally?

Here are my .env settings:
```
NODE_ENV=production
ORIGINS= // what can I specify here for localhost?
OAUTH_CLIENT_ID=GITHUB_CLIENT_ID
OAUTH_CLIENT_SECRET=GITHUB_SECRET
PORT=3001
AUTH_TARGET=_blank
```

**Comment by vencax** [comment]
See: https://github.com/vencax/netlify-cms-github-oauth-provider/issues/27#issuecomment-1621502255
