### ISSUE TITLE
netlify-cms oauth in golang

### ISSUE THREAD

**Issue by igk1972** [vencax/netlify-cms-github-oauth-provider#7]
Hi!
I was inspired by js code, and I created my implementation on Go.

See [netlify-cms-oauth-provider-go](https://github.com/igk1972/netlify-cms-oauth-provider-go)

Maybe it's interesting to someone.

**Comment by vencax** [comment]
Great! Thanks man :+1:  https://github.com/vencax/netlify-cms-github-oauth-provider/commit/79e99d8669ad88349f25500e301c10ce398ef9c1
