### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by tech4him1** [vencax/netlify-cms-github-oauth-provider#9]
Have you considered supporting other Oauth providers/backends like GitLab?

**Comment by tech4him1** [comment]
Ah, I see you say you'll accept PRs for other clients, that's probably the best way to do it :).

**Comment by vencax** [comment]
I think other providers would be supported by configuration. So when somebody finds out a way how to reconfig, he/she should share the results (by updating documentation?).

**Comment by tech4him1** [comment]
Would you allow configuration presets/defaults? For example, someone could set `gitlab` without having to configure all the URLs? Or would you want users to set that all in the config?
